# AdminAreaProtection Configuration
# Version 1.0.1

# Debug mode - set to true to enable detailed logging
debug: false

# Language setting (en_US or ru_RU)
language: "en_US"

# Wand item type (default: 280 = stick)
wandItemType: 280

# Selection cooldown in milliseconds (50-5000)
selectionCooldown: 500

# Visualization duration in seconds
visualizationDuration: 10

# Cache expiry time in minutes
cacheExpiry: 5

# Enable messages for area entry/exit
enableMessages: true

# Undo history size
undoHistorySize: 10

# Particle visualization settings
particleVisualization: true

# Area settings
areaSettings:
  # When true, overlapping areas use AND logic (most restrictive)
  # When false, uses OR logic (least restrictive)
  useMostRestrictiveMerge: true
  description:
    mergeBehavior: "When true, overlapping areas use AND logic (most restrictive). When false, uses OR logic (least restrictive)."
  
  # Maximum length for area titles
  titles:
    maxLength: 100

# LuckPerms integration
luckperms:
  enabled: true
  inheritPermissions: true
  updateInterval: 300
