# AdminAreaProtection Configuration
# Version 1.0.1

# Debug mode - set to true to enable detailed logging
debug: true

# Wand item type (default: 280 = stick)
wandItemType: 280

# Selection cooldown in milliseconds (50-5000)
selectionCooldown: 500

# Visualization duration in seconds
visualizationDuration: 10

# Cache expiry time in minutes
cacheExpiry: 5

# Enable messages for area entry/exit
enableMessages: true

# Undo history size
undoHistorySize: 10

# Particle visualization settings
particleVisualization: true

# Area settings
areaSettings:
  # When true, overlapping areas use AND logic (most restrictive)
  # When false, uses OR logic (least restrictive)
  useMostRestrictiveMerge: true
  description:
    mergeBehavior: "When true, overlapping areas use AND logic (most restrictive). When false, uses OR logic (least restrictive)."

# LuckPerms integration
luckperms:
  enabled: true
  inheritPermissions: true
  updateInterval: 300

# Title settings for area entry/exit
title:
  enter:
    main: "§aEntering {area}"
    subtitle: "Welcome to {area}!"
    fadeIn: 20
    stay: 40
    fadeOut: 20
  leave:
    main: "§eLeaving {area}"
    subtitle: "Goodbye from {area}!"
    fadeIn: 20
    stay: 40
    fadeOut: 20

# Default permissions for new areas
defaultPermissions:
  allowBlockBreak: false
  allowBlockPlace: false
  allowInteract: false
  allowContainer: false
  allowDoors: true
  allowRedstone: true
  allowPvP: false
  allowMonsterDamage: true
  allowAnimalDamage: false
  allowItemDrop: true
  allowItemPickup: true
  allowHunger: true
  allowFallDamage: true
  allowFireDamage: true
  allowMobSpawning: true
  allowExplosions: false
  allowFireSpread: false
  allowLiquidFlow: true
  allowLeafDecay: true
  allowPlantGrowth: true
  allowIceForm: true
  allowIceMelt: true
  allowSnowForm: true
  allowSnowMelt: true
  allowMyceliumSpread: true
  allowGrassSpread: true
  allowCropTrample: false
  allowPistons: true
  allowNoteBlocks: true
  allowEnderPearl: true
  allowVehiclePlace: true
  allowVehicleDestroy: false
  allowVehicleEnter: true
  allowFly: false
  allowGameModeChange: false
  allowXpDrop: true
  allowItemFrameRotate: false
  allowArmorStandManipulate: false
  allowPaintingBreak: false
  allowLeashUse: true
  allowShearing: true
  allowItemUse: true
  allowBucketEmpty: false
  allowBucketFill: false
  allowBonemeal: true
  allowFlintAndSteel: false
  allowBreeding: true
  allowCakeEat: true
  allowBedUse: true
  allowEnchantingTable: true
  allowAnvilUse: true
  allowCauldronUse: true
  allowBrewing: true
  allowBeaconUse: true
  allowCraftingTable: true
  allowCommandBlocks: false
  allowDispensers: true
  allowDroppers: true
  allowHoppers: true
  allowComparators: true
  allowRepeaters: true
  allowObservers: true
  allowDaylightSensors: true
  allowTripwires: true
  allowPressurePlates: true
  allowWeightedPlates: true
  allowTargetBlocks: true
  allowTrappedChests: true
  allowLecterns: true
  allowComposter: true
  allowCampfire: true
  allowLoom: true
  allowStonecutter: true
  allowGrindstone: true
  allowRespawnAnchor: true
  allowSmithingTable: true
  allowCartographyTable: true
  allowFletchingTable: true
  allowBell: true
  allowJukebox: true
  allowNoteBlock: true
  allowFurnace: true
  allowSmoker: true
  allowBlastFurnace: true
  allowBarrel: true
  allowShulkerBox: true
  allowEnderChest: true
  allowHopper: true
  allowDropper: true
  allowDispenser: true
  allowCommandBlock: false
  allowStructureBlock: false
  allowJigsawBlock: false
  allowBeehive: true
  allowHoneycomb: true
  allowHoneyBottle: true
  allowLeadUse: true
  allowNameTag: true
  allowFishing: true
  allowTridentThrow: true
  allowElytraUse: true
  allowChorusFruit: true
  allowTotemUse: true
  allowShieldUse: true
  allowCrossbowUse: true
  allowBowUse: true
  allowTridentUse: true
  allowSnowballThrow: true
  allowEggThrow: true
  allowPotionThrow: true
  allowExperienceBottleThrow: true
  allowEnderPearlThrow: true
  allowFireworkUse: true
  allowBookEdit: true
  allowMapUse: true
  allowCompassUse: true
  allowClockUse: true
  allowSpyglassUse: true

# Permission templates for quick application
permissionTemplates:
  pvp:
    allowPvP: true
    allowMonsterDamage: true
    allowAnimalDamage: true
  
  build:
    allowBlockBreak: true
    allowBlockPlace: true
    allowInteract: true
    allowContainer: true
    allowDoors: true
    allowRedstone: true
    allowItemDrop: true
    allowItemPickup: true
    
  safe:
    allowPvP: false
    allowMonsterDamage: false
    allowFallDamage: false
    allowFireDamage: false
    allowMobSpawning: false
    allowExplosions: false
    allowFireSpread: false
    
  farm:
    allowBlockBreak: true
    allowBlockPlace: true
    allowInteract: true
    allowPlantGrowth: true
    allowBonemeal: true
    allowCropTrample: false
    allowBreeding: true
    allowBucketEmpty: true
    allowBucketFill: true
    
  spawn:
    allowBlockBreak: false
    allowBlockPlace: false
    allowInteract: true
    allowContainer: false
    allowDoors: true
    allowRedstone: false
    allowPvP: false
    allowMonsterDamage: false
    allowAnimalDamage: false
    allowItemDrop: true
    allowItemPickup: true
    allowHunger: false
    allowFallDamage: false
    allowFireDamage: false
    allowMobSpawning: false
    allowExplosions: false
    allowFireSpread: false
    allowFly: true

# Messages
messages:
  prefix: "§8[§6AdminArea§8] §r"
  reload: "§aConfiguration reloaded successfully."
  noPermission: "§cYou don't have permission to use this command."
  areaCreated: "§aArea §e{name}§a created successfully!"
  areaDeleted: "§aArea §e{name}§a deleted successfully!"
  areaExists: "§cAn area with that name already exists."
  areaNotFound: "§cArea §e{name}§c not found."
  selectionRequired: "§cYou need to make a selection first. Use the wand to select two corners."
  selectionComplete: "§aSelection complete! Use §e/area create <name>§a to create an area."
  selectionFirstPoint: "§aFirst point selected at §e{x}, {y}, {z}§a."
  selectionSecondPoint: "§aSecond point selected at §e{x}, {y}, {z}§a."
  wandGiven: "§aYou have been given a selection wand."
  invalidName: "§cInvalid area name. Use only letters, numbers, and underscores."
  prioritySet: "§aPriority for area §e{name}§a set to §e{priority}§a."
  invalidPriority: "§cInvalid priority. Must be a number between 0 and 100."
  toggleUpdated: "§aToggle §e{toggle}§a set to §e{value}§a for area §e{name}§a."
  invalidToggle: "§cInvalid toggle name."
  playerAdded: "§aPlayer §e{player}§a added to area §e{name}§a."
  playerRemoved: "§aPlayer §e{player}§a removed from area §e{name}§a."
  playerNotFound: "§cPlayer §e{player}§c not found."
  groupAdded: "§aGroup §e{group}§a added to area §e{name}§a."
  groupRemoved: "§aGroup §e{group}§a removed from area §e{name}§a."
  groupNotFound: "§cGroup §e{group}§c not found."
  trackAdded: "§aTrack §e{track}§a added to area §e{name}§a."
  trackRemoved: "§aTrack §e{track}§a removed from area §e{name}§a."
  trackNotFound: "§cTrack §e{track}§c not found."
  enterMessage: "§aEntering §e{area}§a."
  leaveMessage: "§aLeaving §e{area}§a."
  bypassEnabled: "§aProtection bypass enabled."
  bypassDisabled: "§aProtection bypass disabled."
  globalProtectionEnabled: "§aGlobal area protection enabled."
  globalProtectionDisabled: "§aGlobal area protection disabled."
  debug:
    enabled: "§aDebug mode enabled."
    disabled: "§aDebug mode disabled."
  permissions:
    debugMode: "§cYou don't have permission to toggle debug mode."
  protection:
    default: "§cYou don't have permission to do that in this area."
    blockBreak: "§cYou don't have permission to break blocks in this area."
    blockPlace: "§cYou don't have permission to place blocks in this area."
    interact: "§cYou don't have permission to interact with blocks in this area."
    container: "§cYou don't have permission to access containers in this area."
    door: "§cYou don't have permission to use doors in this area."
    redstone: "§cYou don't have permission to use redstone in this area."
    pvp: "§cPvP is disabled in this area."
    monsterDamage: "§cYou don't have permission to damage monsters in this area."
    animalDamage: "§cYou don't have permission to damage animals in this area."
    itemDrop: "§cYou don't have permission to drop items in this area."
    itemPickup: "§cYou don't have permission to pick up items in this area."
    fly: "§cFlying is not allowed in this area."
    gameMode: "§cYou can't change game mode in this area."
    vehicleEnter: "§cYou don't have permission to enter vehicles in this area."
    vehiclePlace: "§cYou don't have permission to place vehicles in this area."
    vehicleDestroy: "§cYou don't have permission to destroy vehicles in this area."
    itemFrameRotate: "§cYou don't have permission to rotate item frames in this area."
    armorStand: "§cYou don't have permission to manipulate armor stands in this area."
    painting: "§cYou don't have permission to break paintings in this area."
    leash: "§cYou don't have permission to use leads in this area."
    shear: "§cYou don't have permission to use shears in this area."
    itemUse: "§cYou don't have permission to use that item in this area."
    bucketEmpty: "§cYou don't have permission to empty buckets in this area."
    bucketFill: "§cYou don't have permission to fill buckets in this area."
    bonemeal: "§cYou don't have permission to use bonemeal in this area."
    flintAndSteel: "§cYou don't have permission to use flint and steel in this area."
    breeding: "§cYou don't have permission to breed animals in this area."
    cake: "§cYou don't have permission to eat cake in this area."
    bed: "§cYou don't have permission to use beds in this area."
    enchanting: "§cYou don't have permission to use enchanting tables in this area."
    anvil: "§cYou don't have permission to use anvils in this area."
    cauldron: "§cYou don't have permission to use cauldrons in this area."
    brewing: "§cYou don't have permission to use brewing stands in this area."
    beacon: "§cYou don't have permission to use beacons in this area."
    crafting: "§cYou don't have permission to use crafting tables in this area."