# AdminAreaProtection Configuration

# Debug mode - enables detailed logging
# Set to true to see detailed debug messages about plugin operations
# This is useful for troubleshooting issues or understanding plugin behavior
debug: false

# General settings
debugStackTraces: false  # Set to true to show stack traces in debug mode
enableMessages: true
maxAreaPriority: 100

# Wand settings
defaultAreaSize:
  x: 30000000  # Default world size
  y: 
    min: -64
    max: 320
  z: 30000000
wandItemType: 280  # Item ID for the wand (280 = stick)
particleVisualization: true
visualizationDuration: 10  # seconds
selectionCooldown: 250  # milliseconds between selections
undoHistorySize: 10  # number of undo steps to remember

# Cache settings
cacheExpiry: 5  # minutes before cache entries expire

# Language settings
language: en_US

# Title configuration
title:
  enter:
    fadeIn: 20
    stay: 40
    fadeOut: 20
  leave:
    fadeIn: 20
    stay: 40
    fadeOut: 20

# Area-specific title configurations (overrides default)
areaTitles:
  example_area:
    enter:
      main: "§6Welcome to Example Area, {player}"
      subtitle: "§eEnjoy your stay in {area}!"
    leave:
      main: "§6Come back soon, {player}!"
      subtitle: "§eThank you for visiting {area}!"

# LuckPerms integration
luckperms:
  enabled: true
  inheritPermissions: true
  updateInterval: 300  # seconds between permission updates

# Area Settings
areaSettings:
  useMostRestrictiveMerge: true
  description:
    mergeBehavior: "Determines how overlapping areas handle permissions. When true, uses AND logic (most restrictive). When false, uses OR logic (least restrictive)."
    priority: "Higher priority (0-100) areas override lower priority areas in overlapping spaces."
