name: AdminAreaProtection
version: "1.0"
main: adminarea.AdminAreaProtectionPlugin
api: [1.1.0]
load: POSTWORLD
author: "YoussGm3o8"
description: >
  Admin Area Protection Plugin for MCPE Nukkit servers.
  Provides admin area protection with SQLite persistence and GUI-based management.
commands:
  area:
    description: Manage protected areas
    usage: "/area <create|edit|delete|list|bypass|wand|pos1|pos2|help>"
    permission: adminarea.command.area
    permission-message: "§cYou do not have permission to use this command!"
    aliases: [areaprotect, areaadmin]
    subcommands:
      create:
        description: Create a new area
        usage: /area create
      edit:
        description: Edit an existing area
        usage: /area edit <name>
      delete:
        description: Delete an area
        usage: /area delete <name>
      list:
        description: List all areas
        usage: /area list
      help:
        description: Show help message
        usage: /area help
      pos1:
        description: Set the first position for area creation.
        usage: /area pos1
      pos2:
        description: Set the second position for area creation.
        usage: /area pos2
      wand:
        description: Receive the Area Wand.
        usage: /area wand
      bypass:
        description: Toggle bypass mode (operators only).
        usage: /area bypass

permissions:
  adminarea.command.area:
    description: Allows using area protection commands
    default: op
    children:
      adminarea.command.area.create:
        description: Allows creating areas
        default: op
      adminarea.command.area.edit:
        description: Allows editing areas
        default: op
      adminarea.command.area.delete:
        description: Allows deleting areas
        default: op
      adminarea.command.area.list:
        description: Allows listing areas
        default: op
      adminarea.command.area.bypass:
        description: Allows toggling bypass mode
        default: op
